# Welcome to numpy tut

In [1]:
import numpy as np

In [3]:
d = {'a':24 , 'b':17, 'c':12}
m = max(d.values())
res = [k for k, v in d.items() if v==m]
print(res[0])

a


In [5]:
a = 5
b = 10
print(a * b + a ** b // a)

1953175


In [7]:
myarr = np.array([[3,65555,32,7]], np.int64)  #here with the np.int64 we inc
# the size of the integer ... as now larger int can be entered ... 
# we can also take int8  or 32 as per need
# also float can be used too!

In [8]:
myarr[0,1]

65555

In [9]:
myarr.shape    # this gives the no of rows and the columns

(1, 4)

In [10]:
myarr.dtype

dtype('int64')

In [11]:
myarr[0,3] = 69   # we can modify

In [12]:
myarr

array([[    3, 65555,    32,    69]], dtype=int64)

## Array creation: conversion from other python structures

In [13]:
listarray = np.array([[1,2,3],[5,8,5],[9,3,0]])

In [14]:
listarray

array([[1, 2, 3],
       [5, 8, 5],
       [9, 3, 0]])

In [15]:
listarray[2]

array([9, 3, 0])

In [16]:
listarray.dtype

dtype('int32')

In [18]:
listarray.shape

(3, 3)

In [19]:
listarray.size

9

In [20]:
np.array({34,54,21,21})

array({34, 21, 54}, dtype=object)

In [21]:
# this way the object array gets created!... so in data calculation mainly
# use the int or the float type

## using the instrinsic functions

In [22]:
zeros = np.zeros((4,7))  # this creates the array of assigned length filled
# with the zeros

In [23]:
zeros

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [24]:
zeros.dtype

dtype('float64')

In [25]:
range = np.arange(98)  # this gives the array from the 0 to n-1

In [26]:
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97])

In [27]:
lspace = np.linspace(1,50,7)  # this creates an array of size 7 with 
# numbers from 1 to 50 such that there's equal spacing btw them

In [28]:
lspace

array([ 1.        ,  9.16666667, 17.33333333, 25.5       , 33.66666667,
       41.83333333, 50.        ])

In [29]:
emp = np.empty((4,7))  #creates an empty array

In [30]:
emp

array([[0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0.]])

In [31]:
emp_like = np.empty_like(lspace) # this makes empty array like that of given

In [32]:
emp_like

array([ 1.        ,  9.16666667, 17.33333333, 25.5       , 33.66666667,
       41.83333333, 50.        ])

In [33]:
ide = np.identity(15) # identity matrix of size given

In [34]:
ide

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0.

In [35]:
ide.shape

(15, 15)

In [37]:
# we can reshape the arange in combination of the possibilities as 98 = 7*14
range.reshape(7,14)

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55],
       [56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69],
       [70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83],
       [84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97]])

In [38]:
range # the original not changed until in it changes made
range

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50,
       51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67,
       68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84,
       85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97])

In [ ]:
range = range.reshape(7,14)
range

In [ ]:
# we can again make it straight by ravel
range = range.ravel()
range

In [ ]:
range.shape

## axis of the arrays

# the number of the axes in array is equal to the dimension of array
#### For 1D arrays there is only one axis viz; Axis0
#### and since there is only one direction so this axis0 of 1D array is in the horizontal direction i.e. covering all the columns...
#### for the 2D array there are two axes axis0 and the axis1 ; the axis0 is along the vertical directon covering all the rows and the axis1 is gorizontal here covetering all the columns

In [ ]:
x = [[1,2,3],[4,8,6],[2,45,7]]

In [ ]:
ar = np.array(x)

In [ ]:
ar.sum(axis=0) # adds from all rows...

In [ ]:
ar.sum(axis=1) # adds from all columns...

In [ ]:
ar.T   # transpose

In [ ]:
ar.flat   # this gives an iterator to travel the array

In [ ]:
for item in ar.flat:
    print(item)

In [ ]:
ar.ndim  # this gives no of dimension

In [ ]:
ar.size # the total items

In [ ]:
ar.nbytes # gives the total bytes consumed

In [ ]:
one = np.array([1,2,5,8,69])

In [ ]:
one.argmax() # this gives the index of max element
# () used when it is attribute

In [ ]:
one.argmin() # index of min item

In [ ]:
one.argsort()  # gives the indices order when put then sorted

In [ ]:
ar

In [ ]:
ar.argmin()  # in the 2D array the indexing start from the 0 and go thru
# first row nd then thru the 2nd row till end...

In [ ]:
ar.argmax()

In [ ]:
ar.argmax(axis=0) # in each of the axis0 i.e.in each vertical axis
# the max element's index will be given by starting the index from 0 
# each time starting from the top

In [ ]:
ar.argmax(axis=1)  # simly for the horizontal

In [ ]:
ar.argsort(axis=1)  # this gives indices to sort in horizontal

In [ ]:
ar.ravel()

In [ ]:
ar.reshape(9,1)

In [ ]:
ar2 = np.array([[1,5,9],
              [8,4,-1],
              [2,6,1]])

In [ ]:
ar + ar2  # simply adds the arrays... this ain't possible in lists

In [ ]:
[54,98] + [12,36]

In [ ]:
ar*ar2 # this ain't matrix multiplication, simply multiplying corresponding

In [ ]:
np.sqrt(ar) # element wise square root

In [ ]:
ar.sum()  # sum of all

In [ ]:
ar

In [ ]:
np.where(ar>5)  # gives the tuples of the places where >5... indexing from 0

In [ ]:
np.count_nonzero(ar)  # no of non zeros

In [ ]:
np.nonzero(ar)  # tuples of the non zeros

In [ ]:
import sys  # let see the size comparison

In [ ]:
py_ar = [0,4,8,45]

In [ ]:
np_ar = np.array(py_ar)

In [ ]:
sys.getsizeof(1) * len(py_ar)

In [ ]:
np_ar.itemsize * np_ar.size

In [ ]:
np_ar.tolist()  # converts np array to the list

##### here the array for the negative indexing the indexing starts from the end side... 
##### Also, for the slicing of the arrays there is one more property...Slicing creates an array of indices using a set of three values (start:stop:step).